### ISSUE TITLE
I tried so many times and it continued to threw the same exception:

### ISSUE THREAD

**Issue by Frank-LSY** [ohsu-computational-biology/gdc-scan#1]
I tried so many times and it continued to threw the same exception:

requests.exceptions.SSLError: HTTPSConnectionPool(host='gdc-api.nci.nih.gov', port=443): Max retries exceeded with url: /v0/projects (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')",),))

How to solve it?

**Comment by adamstruck** [comment]
This repo is no longer being actively maintained.  You may just need to change [URL_BASE](https://github.com/ohsu-comp-bio/gdc-scan/blob/master/gdc_scan.py#L9-L10) on line 9 to https://api.gdc.cancer.gov/ to reflect the GDC's new endpoint.

**Comment by Frank-LSY** [comment]
It works! Thank you!
